### ISSUE TITLE
Add support for default backup

### ISSUE THREAD

**Issue by hossainemruz** [appscode/stash#658]
**Tasks:**
- [x] Update workload controllers to handle backup annotations
- [x] Add controller for AppBinding
- [x] Add controller for PVC

**Comment by hossainemruz** [comment]
Done in https://github.com/appscode/stash/pull/675
